# Generated by Django 4.0.3 on 2022-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', max_length=500, upload_to='uploads/'),
        ),
    ]
